network:
  default:
    external:
      name: durga

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb

  catalaogue:
    image: catalaogue:v1
    container_name: catalaogue
    depends_on:
      - mongodb

  web:
    image: web:v1
    container_name: web
    depends_on:
      - 
      

  redis:
    image: redis
    container_name: redis

  user:
    image: user:v1
    container_name: user
    depends_on:
      - redis

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalaogue

  mysql:
    image: mysql:v1
    container_name: mysql

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123


  payment:
    container_name: payment
    image: payment:v1
    depends_on:
    - rabbitmq
    - user
    - cart

